defaultNamespace: traefik

helm:
  chart: traefik
  repo: https://traefik.github.io/charts
  releaseName: traefik-crds
  version: 1.12.0

overrideTargets:
  - clusterSelector:
      matchLabels:
        fleet-app-traefik: "true"
