apiVersion: v1
kind: Service
metadata:
  name: vault-0-internal
spec:
  internalTrafficPolicy: Cluster
  publishNotReadyAddresses: true
  ports:
    - name: http
      port: 8200
      protocol: TCP
      targetPort: 8200
  selector:
    statefulset.kubernetes.io/pod-name: vault-0
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: vault-1-internal
spec:
  internalTrafficPolicy: Cluster
  publishNotReadyAddresses: true
  ports:
    - name: http
      port: 8200
      protocol: TCP
      targetPort: 8200
  selector:
    statefulset.kubernetes.io/pod-name: vault-1
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: vault-2-internal
spec:
  internalTrafficPolicy: Cluster
  publishNotReadyAddresses: true
  ports:
    - name: http
      port: 8200
      protocol: TCP
      targetPort: 8200
  selector:
    statefulset.kubernetes.io/pod-name: vault-2
  type: ClusterIP
