global:
  cattle:
    clusterName: homelab
    rkePathPrefix: ""
    rkeWindowsPathPrefix: ""
    url: https://rancher.suse
ingress:
  enabled: true
  className: traefik
  annotations:
    cert-manager.io/cluster-issuer: local-issuer
  hosts:
    - host: universal-proxy.lab.suse
  tls:
    - secretName: suse-ai-up-tls
      hosts:
        - universal-proxy.lab.suse
initialGroups:
  groups:
    - id: mcp-admins
      name: MCP Administrators
  groups:
    - id: mcp-users
      name: MCP Users
initialUsers:
  users:
    - email: bas@ping6.nl
      groups: mcp-admins
      id: admin
      name: System Administrator
      password: ""
installType: custom
serviceResources: light
