defaultNamespace: cattle-neuvector-system

targetCustomizations:
  - name: traefik-homelab
    clusterSelector:
      matchLabels:
        management.cattle.io/cluster-display-name: homelab
    yaml:
      overlays:
        - traefik
  - name: traefik-demolab
    clusterSelector:
      matchLabels:
        management.cattle.io/cluster-display-name: demolab
    yaml:
      overlays:
        - traefik

overrideTargets:
  - clusterSelector:
      matchLabels:
        fleet-app-neuvector: true
