mode: standalone
persistence:
  size: 25Gi
  storageClass: local-path-ssd
existingSecret: "minio-credentials"
ingress:
  enabled: true
  ingressClassName: nginx
  annotations:
    kubernetes.io/ingress.allow-http: "false"
    kubernetes.io/ingress.global-static-ip-name: ""
    nginx.ingress.kubernetes.io/secure-backends: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/whitelist-source-range: 0.0.0.0/0
    cert-manager.io/cluster-issuer: local-issuer
  path: /
  hosts:
    - s3.lab.suse
  tls:
    - secretName: minio-s3-tls
      hosts:
        - s3.lab.suse
consoleIngress:
  enabled: true
  ingressClassName: nginx
  annotations:
    kubernetes.io/ingress.allow-http: "false"
    kubernetes.io/ingress.global-static-ip-name: ""
    nginx.ingress.kubernetes.io/secure-backends: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/whitelist-source-range: 0.0.0.0/0
    cert-manager.io/cluster-issuer: local-issuer
  path: /
  hosts:
    - minio.lab.suse
  tls:
    - secretName: minio-console-tls
      hosts:
        - minio.lab.suse
