apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: application-collection
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: "{{ .dpapps-secret | toString }}"
    name: application-collection
    creationPolicy: Owner
  data:
    - secretKey: dpapps-secret
      remoteRef:
        key: secretstore.lab.suse
        property: dpapps-secret
