apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: application-collection
spec:
  refreshInterval: 2h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: "{{ .dpappssecret | toString }}"
    name: application-collection
    creationPolicy: Owner
  data:
    - secretKey: dpappssecret
      remoteRef:
        key: secretstore.lab.suse
        property: dpapps-secret
