apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-ssd
provisioner: nfs.csi.k8s.io
parameters:
  server: nas.lan.ping6.nl
  share: /mnt/ssd-storage-pool/nfs
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
