defaultNamespace: traefik

helm:
  chart: traefik
  repo: https://traefik.github.io/charts
  releaseName: traefik
  valuesFiles:
    - values.yaml

overrideTargets:
  - clusterSelector:
      matchLabels:
        fleet-app-traefik: "true"
