apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: neuvector-registry-adapter
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: neuvector-registry-adapter
    kind: ClusterSecretStore
  target:
    name: neuvector-registry-adapter
  data:
    - secretKey: username
      remoteRef:
        key: secretstore.lab.suse
        property: neuvector-registry-adapter-username
    - secretKey: password
      remoteRef:
        key: secretstore.lab.suse
        property: neuvector-registry-adapter-password
