apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minio-credentials-secret
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: minio-credentials
  data:
    - secretKey: rootUser
      remoteRef:
        key: secretstore.lab.suse
        property: minio-root-user
    - secretKey: rootPassword
      remoteRef:
        key: secretstore.lab.suse
        property: minio-root-password
